date: 20240101
sif: /path/to/slopi.sif
refs: cf4
# this file should contain the absolute paths to the bams/crams
# to be used for imputation
bam_list: /path/to/bams.list

breeds:
# - all
  - belgians
  - gshp
  - gtdn
  - stpd_pwdg
  - wssp

refgen:
  cf4:
    name: cf4
    fasta: /home/refgen/dog/canfam4/canFam4.fa
    phased_pop: /path/to/phased.vcf

phased:
  cf4: /path/to/phased_snps_ref.vcf.gz

# canfan4 link map in container
link_map: 
  cf4: /home/refgen/dog/canfam4/canFam4.linkage.map
