
sif: /path/to/slopi.sif

breeds:
# - all
  - belgians
  - gshp
  - gtdn
  - stpd_pwdg
  - wssp

refgen:
  cf4: /home/refgen/dog/canfam4/canFam4.fa

phased:
  cf4: /path/to/phased_snps_ref.vcf.gz

link_map: /home/refgen/dog/canfam4/canFam4.linkage.map
